Sqlcmd -S tcp:sqljames.database.windows.net -d menuthing -U james -P Budza123 -i ./generated/_schemas-sequences.sql
Sqlcmd -S tcp:sqljames.database.windows.net -d menuthing -U james -P Budza123 -i ./generated/_recreate.sql
Sqlcmd -S tcp:sqljames.database.windows.net -d menuthing -U james -P Budza123 -i ./generated/seed/_seed-postcodes.sql
Sqlcmd -S tcp:sqljames.database.windows.net -d menuthing -U james -P Budza123 -i ./generated/seed/_seed-addresses.sql
Sqlcmd -S tcp:sqljames.database.windows.net -d menuthing -U james -P Budza123 -i ./generated/seed/_seed-payment-methods.sql
Sqlcmd -S tcp:sqljames.database.windows.net -d menuthing -U james -P Budza123 -i ./generated/seed/_seed-order-types.sql
Sqlcmd -S tcp:sqljames.database.windows.net -d menuthing -U james -P Budza123 -i ./generated/seed/_seed-person-types.sql
Sqlcmd -S tcp:sqljames.database.windows.net -d menuthing -U james -P Budza123 -i ./generated/seed/_seed-stores.sql
Sqlcmd -S tcp:sqljames.database.windows.net -d menuthing -U james -P Budza123 -i ./generated/seed/_seed-people.sql
Sqlcmd -S tcp:sqljames.database.windows.net -d menuthing -U james -P Budza123 -i ./generated/seed/_seed-reviews.sql
Sqlcmd -S tcp:sqljames.database.windows.net -d menuthing -U james -P Budza123 -i ./generated/seed/_seed-business-hours.sql
Sqlcmd -S tcp:sqljames.database.windows.net -d menuthing -U james -P Budza123 -i ./generated/seed/_seed-products.sql
Sqlcmd -S tcp:sqljames.database.windows.net -d menuthing -U james -P Budza123 -i ./generated/seed/_seed-product-extras.sql
Sqlcmd -S tcp:sqljames.database.windows.net -d menuthing -U james -P Budza123 -i ./generated/seed/_seed-product-options.sql